from __future__ import annotations

import json
from typing import get_args

from fonts import DEFAULT_PAIR, FONT_PAIRS
from layouts import DEFAULT_PACK, DEFAULT_VARIANTS, LAYOUT_PACKS, PACK_DESCRIPTIONS, VARIANTS
from schema import (
    ICON_SECTIONS,
    LIST_FIELDS,
    NOT_IN_NAV,
    PHOTO_SECTIONS,
    PINNED_SECTIONS,
    Provenance,
    SECTION_LABELS,
    SECTION_ORDER,
)

HEADER = "This file is generated by orchestrator/scripts/export_contracts.py -- do not edit."


def build_manifest() -> dict:
    return {
        "sectionOrder": list(SECTION_ORDER),
        "sectionLabels": {kind: SECTION_LABELS[kind] for kind in SECTION_ORDER},
        "pinnedSections": [kind for kind in SECTION_ORDER if kind in PINNED_SECTIONS],
        "iconSections": [kind for kind in SECTION_ORDER if kind in ICON_SECTIONS],
        "photoSections": {kind: PHOTO_SECTIONS[kind] for kind in SECTION_ORDER
                          if kind in PHOTO_SECTIONS},
        "notInNav": [kind for kind in SECTION_ORDER if kind in NOT_IN_NAV],
        "listFields": {kind: list(LIST_FIELDS[kind]) for kind in SECTION_ORDER
                       if kind in LIST_FIELDS},
        "variants": {kind: list(VARIANTS[kind]) for kind in SECTION_ORDER},
        "defaultVariants": {kind: DEFAULT_VARIANTS[kind] for kind in SECTION_ORDER},
        "layoutPacks": {name: {kind: pack[kind] for kind in SECTION_ORDER}
                        for name, pack in LAYOUT_PACKS.items()},
        "packDescriptions": dict(PACK_DESCRIPTIONS),
        "defaultLayoutPack": DEFAULT_PACK,
        "fontPairs": {name: {"heading": pair.heading, "body": pair.body,
                             "character": pair.character}
                      for name, pair in FONT_PAIRS.items()},
        "defaultFontPair": DEFAULT_PAIR,
        "provenance": list(get_args(Provenance)),
    }


def render_ts(manifest: dict) -> str:
    body = json.dumps(manifest, indent=2, ensure_ascii=False)
    return f"// {HEADER}\n\nexport const MANIFEST = {body} as const;\n"
