[pytest]
testpaths = tests
filterwarnings =
    ignore:datetime.datetime.utcnow\(\) is deprecated:DeprecationWarning:mongomock
    ignore:Using `httpx` with `starlette.testclient` is deprecated
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
